name: Get Unity Activation File 🔑

on: workflow_dispatch

jobs:
  activation:
    name: Request Manual Activation File
    runs-on: ubuntu-latest
    steps:
      - name: Request manual activation file
        uses: game-ci/unity-builder@v4
        with:
          entrypoint: /version
          projectPath: Nexus-VR-Game # 👈 Crucial: Points to your Unity project subfolder
          
      - name: Upload activation file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: manual-activation-file
          path: ./*.alf
